global:
  resolve_timeout: 5m

route:
  receiver: 'snowflake-webhook'
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m

receivers:
  - name: 'snowflake-webhook'
    webhook_configs:
      - url: 'http://fastapi-alert-server:8000/webhook/grafana'
        send_resolved: false

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']


