global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'docker-host-monitor'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# Load rules once and periodically evaluate them
rule_files:
  - "alert.rules.yml"
  - "storage_alert.rules.yml"

# A scrape configuration containing exactly one endpoint to scrape
scrape_configs:
  # # Prometheus itself
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090']

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # Node Exporter for host metrics 
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
